doc-warnings: true

ignore-paths:
    - docs

pylint:
    max-line-length: 100

pyflakes:
  run: false

pep257:
  run: true
  disable: 
    - D104
    - D105
    - D107
    - D202
    - D203
    - D204
    - D212
    - D406
    - D407
    - D412
    - D413
